export interface Model {
  region: string
  area: string
  gaCode: string
  gaLocation: string
  gadCode: string
  gadName: string
  openDate: string
  branch: string
  revenueSCCompare: number
  targets10: number
  targets20: number
  targets30: number
  targets50: number
  targets70: number
  targets90: number
  targets105: number
  targets120: number
  revenueSCReachedInTheFourthQuater: number
  tagetsRest10: number
  tagetsRest20: number
  tagetsRest30: number
  tagetsRest50: number
  tagetsRest70: number
  tagetsRest90: number
  tagetsRest105: number
  tagetsRest120: number
  bonusLevelGrowth: number
  bonusLevelGrowthRate: number
  bonusLevelBonusRate: number
  FYPArisesInTheQuarter: number
  bonus: number,
  BDM: string,
  BDD: string
}